In [9]:
# Initialize Otter
import otter
grader = otter.Notebook("hwk1-task2-corals.ipynb")

# Task 2: Exploring coral diversity data

## Instructions 

- First, update the following cell to have a link to *your* Homework 1 GitHub repository:

**UPDATE THIS LINK:**

[https://github.com/nberry18/eds220-hwk1.git]()

- This task covers topics on the lesson on [subsetting `pandas.DataFrames`](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.html). The best strategy to solve it is to get together with your classmates and work on it together after that lecture.

- Review the [complete rubric for this task](https://docs.google.com/document/d/131OnUDOLpOl94SlaMU9nGqT998ABrjFS/edit?usp=sharing&ouid=111507336322611936333&rtpof=true&sd=true) before starting.

- **Make at least 5 commits at moments you think are adequate.** We'll check your repository and view the commit history.

- **Add comments for all your code.** Err on the side of commenting too much for now. Comments should follow best practices.

<!-- BEGIN QUESTION -->


## 1
For this task we are going to use data about  [Western Indian Ocean Coral Diversity (McClanahan, 2023)](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H) from the Knowledge Network for Biocomplexity (KNB) data repository. 

a. Navigate to the dataset's link and explore the data package. 
 
b. Use the next markdown cell to add a brief description of the dataset, including a citation, date of access, and a link to the archive.

_The Western Indian Ocean Coral Diversity (McClanahan, 2023) dataset is accessible through the Knowledge Network for Biocomplexity (KNB) data repo. The data set focuses on 7039 mapped reef cells in the western Indian Ocean. _

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 2
In the next code cell, import the `pandas` package using standard abbreviation in a code cell.

Read in the data from the URL using the `pd.read_csv` function and store it as `coral_div` like this:

```
# read in data
coral_div = pd.read_csv('the URL goes here')
```

In [2]:
import pandas as pd
coral_div = pd.read_csv('data/coral_data.csv')

<!-- END QUESTION -->

## 3

Use attributes and methods of the `coral_div` data frame to obtain the following information about it:

Use the code cells marked a-e. For each, add a comment explaining what is the ouput.

a. how many rows and columns does it have? Store your answers in the `rows` and `columns` variables.

In [6]:
coral_div.shape # `shape` is an atrribute that returns (rows, columns) of a dataframe.

(575, 42)

In [7]:
#a 
rows = 575
columns = 42

In [10]:
grader.check("q3_a")

q3_a results: All test cases passed!

b. What are the column names? Store your answer in the `coral_div_columns` variable.

In [13]:
#b
coral_div_columns = coral_div.columns # `columns` is an attribute that lists all of the columns in the dataframe. 
coral_div_columns

Index(['PU_ID', 'PU_Lat', 'PU_Lon', 'Number_of_genera', 'Country', 'Ecoregion',
       'Management', 'Habitat', 'Observer', 'Depth', 'Coralcover',
       'SSTRateofRise', 'PARmax', 'Calcite', 'Dis_oxygen', 'mean.waveNRJ',
       'Salinity_mean', 'andrello_reef_value', 'andrello_nutrients',
       'mean.npp', 'TT_market_hrs', 'TT_pop_hrs', 'cumDHW', 'SST_Kurtosis',
       'SST_Median', 'ChlorA_median', 'andrello_sediments', 'Current_vel_mean',
       'Diff_attenuation', 'Grav_NP', 'Grav_NC', 'PH', 'SST_bimodality',
       'SST_Skewness', 'ClimateStressModel', 'Netflow', 'Indegree',
       'Outdegree', 'Retention', 'min_yr', 'max_yr', 'no_replicates'],
      dtype='object')

In [14]:
grader.check("q3_b")

q3_b results: All test cases passed!

c. what are the data types of the columns? Store your answer in the `coral_div_types`.

In [16]:
#c
coral_div_types = coral_div.dtypes # `dtypes` is an attribute that describes the type of data in each column.
coral_div_types

PU_ID                    int64
PU_Lat                 float64
PU_Lon                 float64
Number_of_genera         int64
Country                 object
Ecoregion               object
Management              object
Habitat                 object
Observer                object
Depth                  float64
Coralcover               int64
SSTRateofRise          float64
PARmax                 float64
Calcite                float64
Dis_oxygen             float64
mean.waveNRJ           float64
Salinity_mean          float64
andrello_reef_value      int64
andrello_nutrients     float64
mean.npp               float64
TT_market_hrs          float64
TT_pop_hrs             float64
cumDHW                 float64
SST_Kurtosis           float64
SST_Median             float64
ChlorA_median          float64
andrello_sediments     float64
Current_vel_mean       float64
Diff_attenuation       float64
Grav_NP                float64
Grav_NC                float64
PH                     float64
SST_bimodality         float64
SST_Skewness           float64
ClimateStressModel     float64
Netflow                float64
Indegree               float64
Outdegree              float64
Retention              float64
min_yr                   int64
max_yr                   int64
no_replicates            int64
dtype: object

In [17]:
grader.check("q3_c")

q3_c results: All test cases passed!

d. display the first 8 rows with all the column names. For this one, you will need to udpate a `pandas` option (HINT: check the first discussion section). Store your answer in the `first_8_rows` variable.

In [20]:
#d
first_8_rows = coral_div.head(8) # `head(n)` is a function that returns the first n number of rows of the data frame, 
# without n denoted it defaults to returning the first 5 rows.

In [21]:
# View the dataframe 
first_8_rows

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,...,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,...,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [22]:
grader.check("q3_d")

q3_d results: All test cases passed!

<!-- BEGIN QUESTION -->

e. Write code to find out some other inital information you are interested in.

In [24]:
# e
print(coral_div.info()) # `info()` returns the non-null count for each column in the dataframe as well as the data type. 
print(coral_div.nunique()) # `nunique()` returns the distinct values that appear in each column of the datdframe.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575 entries, 0 to 574
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PU_ID                575 non-null    int64
 1   PU_Lat               575 non-null    float64
 2   PU_Lon               575 non-null    float64
 3   Number_of_genera     575 non-null    int64
 4   Country              575 non-null    object
 5   Ecoregion            575 non-null    object
 6   Management           575 non-null    object
 7   Habitat              530 non-null    object
 8   Observer             575 non-null    object
 9   Depth                575 non-null    float64
 10  Coralcover           575 non-null    int64
 11  SSTRateofRise        575 non-null    float64
 12  PARmax               575 non-null    float64
 13  Calcite              575 non-null    float64
 14  Dis_oxygen           575 non-null    float64
 15  mean.waveNRJ         575 non-null    float64
 16  Salinity_mean        575 non-null    float64
 17  andrello_reef_value  575 non-null    int64
 18  andrello_nutrients   575 non-null    float64
 19  mean.npp             575 non-null    float64
 20  TT_market_hrs        575 non-null    float64
 21  TT_pop_hrs           575 non-null    float64
 22  cumDHW               575 non-null    float64
 23  SST_Kurtosis         575 non-null    float64
 24  SST_Median           575 non-null    float64
 25  ChlorA_median        575 non-null    float64
 26  andrello_sediments   575 non-null    float64
 27  Current_vel_mean     567 non-null    float64
 28  Diff_attenuation     575 non-null    float64
 29  Grav_NP              575 non-null    float64
 30  Grav_NC              575 non-null    float64
 31  PH                   575 non-null    float64
 32  SST_bimodality       575 non-null    float64
 33  SST_Skewness         575 non-null    float64
 34  ClimateStressModel   575 non-null    float64
 35  Netflow              575 non-null    float64
 36  Indegree             575 non-null    float64
 37  Outdegree            575 non-null    float64
 38  Retention            575 non-null    float64
 39  min_yr               575 non-null    int64
 40  max_yr               575 non-null    int64
 41  no_replicates        575 non-null    int64
dtypes: float64(30), int64(7), object(5)
memory usage: 188.8+ KB
None
PU_ID                  304
PU_Lat                 152
PU_Lon                 217
Number_of_genera        37
Country                 11
Ecoregion                6
Management               4
Habitat                  6
Observer                16
Depth                  111
Coralcover              46
SSTRateofRise          283
PARmax                 221
Calcite                219
Dis_oxygen             187
mean.waveNRJ           237
Salinity_mean          226
andrello_reef_value    139
andrello_nutrients     165
mean.npp               197
TT_market_hrs          129
TT_pop_hrs              51
cumDHW                 283
SST_Kurtosis           283
SST_Median             193
ChlorA_median          283
andrello_sediments     180
Current_vel_mean       224
Diff_attenuation       165
Grav_NP                168
Grav_NC                169
PH                      62
SST_bimodality         282
SST_Skewness           283
ClimateStressModel     297
Netflow                126
Indegree               110
Outdegree              106
Retention              109
min_yr                  19
max_yr                  19
no_replicates           12
dtype: int64

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 4

Some of the columns have data type `int64` and some have data type `float64`. What is the difference between these `int64` and `float64`?

_`int64` is data that is only whole numbers with no decimal places. `float64` is a number with a decimal place. For example, 11 would be classified as an `int64` since it is a whole number, however if it was inputted into a dataframe as 11.0 instead then it would be classified as `float64` since there is a decimal point in the number._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 5

The `Country` column indicates the country where the coral reef is located. Explain, in your own words, what is the ouput of `coral_div['Country']` and `coral_div['Country'].unique()`.

_`coral_div['Country']`: returns all of the values (rows) in the column 'Country'. The brackets [] are used to access the values in the column.
`coral_div['Country'].unique()`: extracts and returns all of the unique values from a list. In this case it is all of the unique values within the column noted in the brackets []. _

<!-- END QUESTION -->

## 6

Check the dataset's [metadata file README_md.doc](https://knb.ecoinformatics.org/view/doi:10.5063/F1K35S3H) to find which column has information about who made an observation. How many observers collected this data? HINT: Check this [method for `pandas.DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html). Store your answer in the `unique_observers` variable.

In [34]:
coral_div['Observer'].nunique() # `.nunique` returns the number of unique values while `.unique` all of lists the unique values.

16

In [35]:
unique_observers = coral_div['Observer'].nunique()

In [36]:
grader.check("q6")

q6 results: All test cases passed!

## 7

The `Coralcover` column indicates the percent of hard coral cover in each 6 km reef cell surveyed.

<!-- BEGIN QUESTION -->

a)  Describe, in detail,  what kind of object `coral_div['Coralcover']>= 50` is.

_Type your answer here, replacing this text._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

b) What data is `coral_div[coral_div['Coralcover'] >= 50]` selecting?

_Type your answer here, replacing this text._

<!-- END QUESTION -->

## 8

Use code to find if there are there any sites with a 30% coral cover in Tanzania. Store your answer in the `coral_cover` variable.

In [61]:
pd.set_option("display.max_columns", None) # change pandas settings to show all columns in a dataframe.

In [58]:
coral_cover = coral_div[(coral_div['Coralcover'] == 30) & (coral_div['Country'] == 'Tanzania')] # combine multiple conditions to select rows by 
# surrounding each one in parentheses () and using the operator &

In [59]:
# View the dataframe
coral_cover

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
63,693,39.391121,-5.782490,10,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,5.000000,30,0.015676,52.992001,0.037043,4.7580,5.885771,35.099083,1156,1.507334,958.495666,0.950000,0.550000,30.656667,-0.940944,27.3625,0.225574,26.068680,0.716784,0.0730,0.004944,0.779117,8.215,0.490512,-0.101724,0.655600,-0.309514,77.00,65.25,147.50,2018,2018,2
64,697,39.391121,-5.804983,22,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.166667,30,0.015599,52.992001,0.037043,4.7580,5.285148,35.099083,1156,1.507334,968.100098,0.950000,0.550000,30.021056,-0.942581,27.3600,0.217308,26.068680,0.716784,0.0730,0.004944,0.779117,8.215,0.490769,-0.100365,0.683050,-0.309514,77.00,65.25,147.50,2010,2018,3
341,4294,39.211458,-4.814515,37,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,30,0.018789,53.858002,0.002154,4.7170,3.129188,35.120766,0,1.233231,996.539490,1.216667,0.266667,23.736330,-0.779552,27.2450,0.470832,1746.570435,0.653534,0.1210,0.004043,42.349168,8.216,0.451293,-0.048992,0.608900,0.514920,46.00,49.50,82.75,2018,2018,1
342,4299,39.233916,-4.837043,26,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,12.500000,30,0.018789,53.937000,0.001265,4.7195,2.233872,35.125887,0,1.233231,1018.213928,1.550000,0.566667,23.736330,-0.779552,27.2500,0.462739,1746.570435,0.653883,0.1115,0.000879,25.914153,8.216,0.451293,-0.048992,0.601725,0.514920,46.00,49.50,82.75,2018,2018,2
343,4302,39.211458,-4.859570,31,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,7.000000,30,0.018462,54.015999,0.000377,4.7220,0.179306,35.131008,0,1.233231,1071.519775,1.550000,0.566667,23.285391,-0.784669,27.2600,0.469467,1746.570435,0.654233,0.1020,0.000879,25.914153,8.216,0.452402,-0.050477,0.595200,0.514920,46.00,49.50,82.75,2018,2018,1
344,4303,39.301290,-4.859570,23,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,30,0.018270,53.937000,0.002104,4.7220,2.600268,35.174747,0,0.611645,965.657349,1.733333,0.800000,24.659219,-0.792062,27.2550,0.339959,858.381897,0.738552,0.0960,0.000426,20.656527,8.216,0.453806,-0.048007,0.602300,0.514920,46.00,49.50,82.75,2018,2018,1
377,4906,39.660616,-4.972195,33,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.000000,30,0.016549,53.943001,0.000076,4.7270,0.034857,34.968960,345,0.063687,980.656921,1.550000,0.700000,27.144278,-0.941926,27.2150,0.212634,23.135084,0.234671,0.0620,0.038530,3.044183,8.213,0.488396,-0.074229,0.671900,0.156359,66.75,41.75,38.00,2013,2013,2
388,5049,39.615700,-5.490011,14,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,4.000000,30,0.015241,52.493000,0.000155,4.7485,8.124817,34.976822,0,0.104816,755.473267,2.066667,0.583333,26.566285,-0.935094,25.7150,0.158397,9.305736,0.406605,0.0625,0.003125,1.727036,8.213,0.489921,-0.109523,0.657000,-0.328399,93.25,57.25,650.25,2018,2018,1
389,5050,39.638158,-5.490011,18,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,6.000000,30,0.015241,52.493000,0.000155,4.7485,8.124817,34.976822,0,0.104816,755.473267,2.066667,0.583333,26.566285,-0.935094,25.7100,0.224526,9.305736,0.406605,0.0625,0.003125,1.727036,8.213,0.489921,-0.109523,0.618825,-0.328399,93.25,57.25,650.25,2018,2018,1

In [60]:
grader.check("q8")

q8 results: All test cases passed!

## 9

We are interested in looking at the PH of sea water (`PH` column),  mean salinity (`Salinity_mean` column), and depth of survey location in meters (`Depth` column). Subset the data frame by selecting only these column. Store your answer in the `filtered_data` variable

In [ ]:
filtered_data = ...

In [ ]:
# View the dataframe
filtered_data.head()

In [ ]:
grader.check("q9")

## 10
The `max_yr` column indicates the year of last sampling at a given site. Select the PH, salinity, and depth for sites where sampling ended in 2017. Store your answer in the `sampling_2017` variable. `Sampling_2017` should include the following columns in the following order: ` PH, Salinity_mean, Depth, max_yr`.

In [ ]:
sampling_2017 = ...

In [ ]:
# View the dataframe 
sampling_2017

In [ ]:
grader.check("q10")

## 11
Use `iloc` to select rows 95 through 100 (including 100) in the 17th, 20th, and 28th columns and assign these values to a new variable called `subset`. View the new `subset` dataframe.

HINT: the ouput columns should be `Salinity_mean`, `mean.npp` and `Current_vel_mean` (in that order!).

In [ ]:
subset = ...

In [ ]:
# View the dataframe
subset

In [ ]:
grader.check("q11")

<!-- BEGIN QUESTION -->

## 12 

Run `subset.isna()`. Explain what this code does and what the output represents.

_Type your answer here, replacing this text._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 13
Run `subset.isna().any()`. Explain in your own words what this code does and what the output represents. HINT: check the [documentation of `pandas.Sries.any`](https://pandas.pydata.org/docs/reference/api/pandas.Series.any.html).

_Type your answer here, replacing this text._

<!-- END QUESTION -->

## 14 

Select the rows in `subset` that have NA in the `Current_vel_mean` column. Store your answer in the `subset_na` variable.

In [ ]:
subset_na = ...

In [ ]:
# View the dataframe 
subset_na

In [ ]:
grader.check("q14")

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()